# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dir
  workingDirectory: 'DatingApp.API'
  displayName: List contents of a folder
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: 'DatingApp.API/DatingApp.API.csproj'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
