# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'ffe89bd5-c7d8-4b58-acc4-7ddbdb2e9e96'
    definition: '11'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'ffe89bd5-c7d8-4b58-acc4-7ddbdb2e9e96'
    definition: '12'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)/wwwroot'
- task: PublishBuildArtifacts@1