# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core



trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- script: dir
  workingDirectory: 'DatingApp-SPA/'
  displayName: List contents of a folder

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'DatingApp-SPA/'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build --prod
    workingDir: DatingApp-SPA/  

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'DatingApp-SPA/src/dist'

- task: PublishBuildArtifacts@1
- script: dir
  workingDirectory: 'DatingApp.API/'
  displayName: List contents of a folder

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build

  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: PublishFiles
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release'
    zipAfterPublish: true

- task: CopyFiles@2
  inputs:
    contents: '**/**'
    targetFolder: '$(build.artifactStagingDirectory)'    